// <auto-generated />
using System;
using BookFlow.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookFlow.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909170705_AddLoan")]
    partial class AddLoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookFlow.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CopyNumber")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("BookCopies", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 39,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 42,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CD",
                            Name = "Congo, Democratic Republic of the"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 56,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58,
                            Code = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Code = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 72,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 74,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 75,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 76,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 77,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 78,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 79,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 80,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 84,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 93,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 94,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 95,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 96,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 98,
                            Code = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 99,
                            Code = "VA",
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = 100,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 101,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 102,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 104,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 105,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 108,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 109,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 110,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 111,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 112,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 113,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 114,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 115,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 119,
                            Code = "KP",
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 120,
                            Code = "KR",
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 121,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 122,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 128,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 129,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 130,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 131,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 134,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 137,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 145,
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 147,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 149,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 150,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 152,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 166,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 167,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 168,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PS",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 177,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 178,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 179,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 180,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 182,
                            Code = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 183,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 184,
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 185,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 186,
                            Code = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 187,
                            Code = "SH",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 188,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 189,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 190,
                            Code = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 191,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 192,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 193,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 195,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 198,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 199,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 200,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 201,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 202,
                            Code = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 203,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 207,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 208,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 209,
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 210,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 211,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 212,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 213,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 214,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 215,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 216,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 217,
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 225,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 226,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 227,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 228,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 229,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 230,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 231,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 232,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 233,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 234,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 235,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 236,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 237,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 238,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 242,
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 243,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 244,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 245,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 246,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 247,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 248,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 249,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Author", b =>
                {
                    b.HasOne("BookFlow.Core.Entities.Country", "Country")
                        .WithMany("Authors")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Book", b =>
                {
                    b.HasOne("BookFlow.Core.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookFlow.Core.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.BookCopy", b =>
                {
                    b.HasOne("BookFlow.Core.Entities.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlow.Core.Entities.Member", null)
                        .WithMany("BookCopies")
                        .HasForeignKey("MemberId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Loan", b =>
                {
                    b.HasOne("BookFlow.Core.Entities.BookCopy", "BookCopy")
                        .WithMany("Loans")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookFlow.Core.Entities.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.BookCopy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Country", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("BookFlow.Core.Entities.Member", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
